/**
 * Full international country dataset (name, ISO2 code, flag emoji, dialing
 * code), sorted alphabetically by common name and defaulting to Saudi
 * Arabia. This is a pre-generated snapshot derived from the `world-countries`
 * package rather than a runtime import of it — that package bundles a lot
 * of unrelated data (translations, borders, currencies, etc.) which would
 * otherwise bloat the client bundle by hundreds of kB for a handful of
 * fields. A few dependent-territory dial codes that the raw dataset gets
 * wrong (e.g. Åland, Vatican City, Western Sahara) are corrected here.
 */
export interface Country {
  name: string;
  iso2: string;
  flag: string;
  dialCode: string; // e.g. "+966", no spaces
}

export const countries: Country[] = [
  { name: 'Afghanistan', iso2: 'AF', flag: '🇦🇫', dialCode: '+93' },
  { name: 'Åland Islands', iso2: 'AX', flag: '🇦🇽', dialCode: '+358' },
  { name: 'Albania', iso2: 'AL', flag: '🇦🇱', dialCode: '+355' },
  { name: 'Algeria', iso2: 'DZ', flag: '🇩🇿', dialCode: '+213' },
  { name: 'American Samoa', iso2: 'AS', flag: '🇦🇸', dialCode: '+1684' },
  { name: 'Andorra', iso2: 'AD', flag: '🇦🇩', dialCode: '+376' },
  { name: 'Angola', iso2: 'AO', flag: '🇦🇴', dialCode: '+244' },
  { name: 'Anguilla', iso2: 'AI', flag: '🇦🇮', dialCode: '+1264' },
  { name: 'Antigua and Barbuda', iso2: 'AG', flag: '🇦🇬', dialCode: '+1268' },
  { name: 'Argentina', iso2: 'AR', flag: '🇦🇷', dialCode: '+54' },
  { name: 'Armenia', iso2: 'AM', flag: '🇦🇲', dialCode: '+374' },
  { name: 'Aruba', iso2: 'AW', flag: '🇦🇼', dialCode: '+297' },
  { name: 'Australia', iso2: 'AU', flag: '🇦🇺', dialCode: '+61' },
  { name: 'Austria', iso2: 'AT', flag: '🇦🇹', dialCode: '+43' },
  { name: 'Azerbaijan', iso2: 'AZ', flag: '🇦🇿', dialCode: '+994' },
  { name: 'Bahamas', iso2: 'BS', flag: '🇧🇸', dialCode: '+1242' },
  { name: 'Bahrain', iso2: 'BH', flag: '🇧🇭', dialCode: '+973' },
  { name: 'Bangladesh', iso2: 'BD', flag: '🇧🇩', dialCode: '+880' },
  { name: 'Barbados', iso2: 'BB', flag: '🇧🇧', dialCode: '+1246' },
  { name: 'Belarus', iso2: 'BY', flag: '🇧🇾', dialCode: '+375' },
  { name: 'Belgium', iso2: 'BE', flag: '🇧🇪', dialCode: '+32' },
  { name: 'Belize', iso2: 'BZ', flag: '🇧🇿', dialCode: '+501' },
  { name: 'Benin', iso2: 'BJ', flag: '🇧🇯', dialCode: '+229' },
  { name: 'Bermuda', iso2: 'BM', flag: '🇧🇲', dialCode: '+1441' },
  { name: 'Bhutan', iso2: 'BT', flag: '🇧🇹', dialCode: '+975' },
  { name: 'Bolivia', iso2: 'BO', flag: '🇧🇴', dialCode: '+591' },
  { name: 'Bosnia and Herzegovina', iso2: 'BA', flag: '🇧🇦', dialCode: '+387' },
  { name: 'Botswana', iso2: 'BW', flag: '🇧🇼', dialCode: '+267' },
  { name: 'Bouvet Island', iso2: 'BV', flag: '🇧🇻', dialCode: '+47' },
  { name: 'Brazil', iso2: 'BR', flag: '🇧🇷', dialCode: '+55' },
  { name: 'British Indian Ocean Territory', iso2: 'IO', flag: '🇮🇴', dialCode: '+246' },
  { name: 'British Virgin Islands', iso2: 'VG', flag: '🇻🇬', dialCode: '+1284' },
  { name: 'Brunei', iso2: 'BN', flag: '🇧🇳', dialCode: '+673' },
  { name: 'Bulgaria', iso2: 'BG', flag: '🇧🇬', dialCode: '+359' },
  { name: 'Burkina Faso', iso2: 'BF', flag: '🇧🇫', dialCode: '+226' },
  { name: 'Burundi', iso2: 'BI', flag: '🇧🇮', dialCode: '+257' },
  { name: 'Cambodia', iso2: 'KH', flag: '🇰🇭', dialCode: '+855' },
  { name: 'Cameroon', iso2: 'CM', flag: '🇨🇲', dialCode: '+237' },
  { name: 'Canada', iso2: 'CA', flag: '🇨🇦', dialCode: '+1' },
  { name: 'Cape Verde', iso2: 'CV', flag: '🇨🇻', dialCode: '+238' },
  { name: 'Caribbean Netherlands', iso2: 'BQ', flag: '🇧🇶', dialCode: '+599' },
  { name: 'Cayman Islands', iso2: 'KY', flag: '🇰🇾', dialCode: '+1345' },
  { name: 'Central African Republic', iso2: 'CF', flag: '🇨🇫', dialCode: '+236' },
  { name: 'Chad', iso2: 'TD', flag: '🇹🇩', dialCode: '+235' },
  { name: 'Chile', iso2: 'CL', flag: '🇨🇱', dialCode: '+56' },
  { name: 'China', iso2: 'CN', flag: '🇨🇳', dialCode: '+86' },
  { name: 'Christmas Island', iso2: 'CX', flag: '🇨🇽', dialCode: '+61' },
  { name: 'Cocos (Keeling) Islands', iso2: 'CC', flag: '🇨🇨', dialCode: '+61' },
  { name: 'Colombia', iso2: 'CO', flag: '🇨🇴', dialCode: '+57' },
  { name: 'Comoros', iso2: 'KM', flag: '🇰🇲', dialCode: '+269' },
  { name: 'Cook Islands', iso2: 'CK', flag: '🇨🇰', dialCode: '+682' },
  { name: 'Costa Rica', iso2: 'CR', flag: '🇨🇷', dialCode: '+506' },
  { name: 'Croatia', iso2: 'HR', flag: '🇭🇷', dialCode: '+385' },
  { name: 'Cuba', iso2: 'CU', flag: '🇨🇺', dialCode: '+53' },
  { name: 'Curaçao', iso2: 'CW', flag: '🇨🇼', dialCode: '+599' },
  { name: 'Cyprus', iso2: 'CY', flag: '🇨🇾', dialCode: '+357' },
  { name: 'Czechia', iso2: 'CZ', flag: '🇨🇿', dialCode: '+420' },
  { name: 'Denmark', iso2: 'DK', flag: '🇩🇰', dialCode: '+45' },
  { name: 'Djibouti', iso2: 'DJ', flag: '🇩🇯', dialCode: '+253' },
  { name: 'Dominica', iso2: 'DM', flag: '🇩🇲', dialCode: '+1767' },
  { name: 'Dominican Republic', iso2: 'DO', flag: '🇩🇴', dialCode: '+1' },
  { name: 'DR Congo', iso2: 'CD', flag: '🇨🇩', dialCode: '+243' },
  { name: 'Ecuador', iso2: 'EC', flag: '🇪🇨', dialCode: '+593' },
  { name: 'Egypt', iso2: 'EG', flag: '🇪🇬', dialCode: '+20' },
  { name: 'El Salvador', iso2: 'SV', flag: '🇸🇻', dialCode: '+503' },
  { name: 'Equatorial Guinea', iso2: 'GQ', flag: '🇬🇶', dialCode: '+240' },
  { name: 'Eritrea', iso2: 'ER', flag: '🇪🇷', dialCode: '+291' },
  { name: 'Estonia', iso2: 'EE', flag: '🇪🇪', dialCode: '+372' },
  { name: 'Eswatini', iso2: 'SZ', flag: '🇸🇿', dialCode: '+268' },
  { name: 'Ethiopia', iso2: 'ET', flag: '🇪🇹', dialCode: '+251' },
  { name: 'Falkland Islands', iso2: 'FK', flag: '🇫🇰', dialCode: '+500' },
  { name: 'Faroe Islands', iso2: 'FO', flag: '🇫🇴', dialCode: '+298' },
  { name: 'Fiji', iso2: 'FJ', flag: '🇫🇯', dialCode: '+679' },
  { name: 'Finland', iso2: 'FI', flag: '🇫🇮', dialCode: '+358' },
  { name: 'France', iso2: 'FR', flag: '🇫🇷', dialCode: '+33' },
  { name: 'French Guiana', iso2: 'GF', flag: '🇬🇫', dialCode: '+594' },
  { name: 'French Polynesia', iso2: 'PF', flag: '🇵🇫', dialCode: '+689' },
  { name: 'French Southern and Antarctic Lands', iso2: 'TF', flag: '🇹🇫', dialCode: '+262' },
  { name: 'Gabon', iso2: 'GA', flag: '🇬🇦', dialCode: '+241' },
  { name: 'Gambia', iso2: 'GM', flag: '🇬🇲', dialCode: '+220' },
  { name: 'Georgia', iso2: 'GE', flag: '🇬🇪', dialCode: '+995' },
  { name: 'Germany', iso2: 'DE', flag: '🇩🇪', dialCode: '+49' },
  { name: 'Ghana', iso2: 'GH', flag: '🇬🇭', dialCode: '+233' },
  { name: 'Gibraltar', iso2: 'GI', flag: '🇬🇮', dialCode: '+350' },
  { name: 'Greece', iso2: 'GR', flag: '🇬🇷', dialCode: '+30' },
  { name: 'Greenland', iso2: 'GL', flag: '🇬🇱', dialCode: '+299' },
  { name: 'Grenada', iso2: 'GD', flag: '🇬🇩', dialCode: '+1473' },
  { name: 'Guadeloupe', iso2: 'GP', flag: '🇬🇵', dialCode: '+590' },
  { name: 'Guam', iso2: 'GU', flag: '🇬🇺', dialCode: '+1671' },
  { name: 'Guatemala', iso2: 'GT', flag: '🇬🇹', dialCode: '+502' },
  { name: 'Guernsey', iso2: 'GG', flag: '🇬🇬', dialCode: '+44' },
  { name: 'Guinea', iso2: 'GN', flag: '🇬🇳', dialCode: '+224' },
  { name: 'Guinea-Bissau', iso2: 'GW', flag: '🇬🇼', dialCode: '+245' },
  { name: 'Guyana', iso2: 'GY', flag: '🇬🇾', dialCode: '+592' },
  { name: 'Haiti', iso2: 'HT', flag: '🇭🇹', dialCode: '+509' },
  { name: 'Honduras', iso2: 'HN', flag: '🇭🇳', dialCode: '+504' },
  { name: 'Hong Kong', iso2: 'HK', flag: '🇭🇰', dialCode: '+852' },
  { name: 'Hungary', iso2: 'HU', flag: '🇭🇺', dialCode: '+36' },
  { name: 'Iceland', iso2: 'IS', flag: '🇮🇸', dialCode: '+354' },
  { name: 'India', iso2: 'IN', flag: '🇮🇳', dialCode: '+91' },
  { name: 'Indonesia', iso2: 'ID', flag: '🇮🇩', dialCode: '+62' },
  { name: 'Iran', iso2: 'IR', flag: '🇮🇷', dialCode: '+98' },
  { name: 'Iraq', iso2: 'IQ', flag: '🇮🇶', dialCode: '+964' },
  { name: 'Ireland', iso2: 'IE', flag: '🇮🇪', dialCode: '+353' },
  { name: 'Isle of Man', iso2: 'IM', flag: '🇮🇲', dialCode: '+44' },
  { name: 'Israel', iso2: 'IL', flag: '🇮🇱', dialCode: '+972' },
  { name: 'Italy', iso2: 'IT', flag: '🇮🇹', dialCode: '+39' },
  { name: 'Ivory Coast', iso2: 'CI', flag: '🇨🇮', dialCode: '+225' },
  { name: 'Jamaica', iso2: 'JM', flag: '🇯🇲', dialCode: '+1876' },
  { name: 'Japan', iso2: 'JP', flag: '🇯🇵', dialCode: '+81' },
  { name: 'Jersey', iso2: 'JE', flag: '🇯🇪', dialCode: '+44' },
  { name: 'Jordan', iso2: 'JO', flag: '🇯🇴', dialCode: '+962' },
  { name: 'Kazakhstan', iso2: 'KZ', flag: '🇰🇿', dialCode: '+7' },
  { name: 'Kenya', iso2: 'KE', flag: '🇰🇪', dialCode: '+254' },
  { name: 'Kiribati', iso2: 'KI', flag: '🇰🇮', dialCode: '+686' },
  { name: 'Kosovo', iso2: 'XK', flag: '🇽🇰', dialCode: '+383' },
  { name: 'Kuwait', iso2: 'KW', flag: '🇰🇼', dialCode: '+965' },
  { name: 'Kyrgyzstan', iso2: 'KG', flag: '🇰🇬', dialCode: '+996' },
  { name: 'Laos', iso2: 'LA', flag: '🇱🇦', dialCode: '+856' },
  { name: 'Latvia', iso2: 'LV', flag: '🇱🇻', dialCode: '+371' },
  { name: 'Lebanon', iso2: 'LB', flag: '🇱🇧', dialCode: '+961' },
  { name: 'Lesotho', iso2: 'LS', flag: '🇱🇸', dialCode: '+266' },
  { name: 'Liberia', iso2: 'LR', flag: '🇱🇷', dialCode: '+231' },
  { name: 'Libya', iso2: 'LY', flag: '🇱🇾', dialCode: '+218' },
  { name: 'Liechtenstein', iso2: 'LI', flag: '🇱🇮', dialCode: '+423' },
  { name: 'Lithuania', iso2: 'LT', flag: '🇱🇹', dialCode: '+370' },
  { name: 'Luxembourg', iso2: 'LU', flag: '🇱🇺', dialCode: '+352' },
  { name: 'Macau', iso2: 'MO', flag: '🇲🇴', dialCode: '+853' },
  { name: 'Madagascar', iso2: 'MG', flag: '🇲🇬', dialCode: '+261' },
  { name: 'Malawi', iso2: 'MW', flag: '🇲🇼', dialCode: '+265' },
  { name: 'Malaysia', iso2: 'MY', flag: '🇲🇾', dialCode: '+60' },
  { name: 'Maldives', iso2: 'MV', flag: '🇲🇻', dialCode: '+960' },
  { name: 'Mali', iso2: 'ML', flag: '🇲🇱', dialCode: '+223' },
  { name: 'Malta', iso2: 'MT', flag: '🇲🇹', dialCode: '+356' },
  { name: 'Marshall Islands', iso2: 'MH', flag: '🇲🇭', dialCode: '+692' },
  { name: 'Martinique', iso2: 'MQ', flag: '🇲🇶', dialCode: '+596' },
  { name: 'Mauritania', iso2: 'MR', flag: '🇲🇷', dialCode: '+222' },
  { name: 'Mauritius', iso2: 'MU', flag: '🇲🇺', dialCode: '+230' },
  { name: 'Mayotte', iso2: 'YT', flag: '🇾🇹', dialCode: '+262' },
  { name: 'Mexico', iso2: 'MX', flag: '🇲🇽', dialCode: '+52' },
  { name: 'Micronesia', iso2: 'FM', flag: '🇫🇲', dialCode: '+691' },
  { name: 'Moldova', iso2: 'MD', flag: '🇲🇩', dialCode: '+373' },
  { name: 'Monaco', iso2: 'MC', flag: '🇲🇨', dialCode: '+377' },
  { name: 'Mongolia', iso2: 'MN', flag: '🇲🇳', dialCode: '+976' },
  { name: 'Montenegro', iso2: 'ME', flag: '🇲🇪', dialCode: '+382' },
  { name: 'Montserrat', iso2: 'MS', flag: '🇲🇸', dialCode: '+1664' },
  { name: 'Morocco', iso2: 'MA', flag: '🇲🇦', dialCode: '+212' },
  { name: 'Mozambique', iso2: 'MZ', flag: '🇲🇿', dialCode: '+258' },
  { name: 'Myanmar', iso2: 'MM', flag: '🇲🇲', dialCode: '+95' },
  { name: 'Namibia', iso2: 'NA', flag: '🇳🇦', dialCode: '+264' },
  { name: 'Nauru', iso2: 'NR', flag: '🇳🇷', dialCode: '+674' },
  { name: 'Nepal', iso2: 'NP', flag: '🇳🇵', dialCode: '+977' },
  { name: 'Netherlands', iso2: 'NL', flag: '🇳🇱', dialCode: '+31' },
  { name: 'New Caledonia', iso2: 'NC', flag: '🇳🇨', dialCode: '+687' },
  { name: 'New Zealand', iso2: 'NZ', flag: '🇳🇿', dialCode: '+64' },
  { name: 'Nicaragua', iso2: 'NI', flag: '🇳🇮', dialCode: '+505' },
  { name: 'Niger', iso2: 'NE', flag: '🇳🇪', dialCode: '+227' },
  { name: 'Nigeria', iso2: 'NG', flag: '🇳🇬', dialCode: '+234' },
  { name: 'Niue', iso2: 'NU', flag: '🇳🇺', dialCode: '+683' },
  { name: 'Norfolk Island', iso2: 'NF', flag: '🇳🇫', dialCode: '+672' },
  { name: 'North Korea', iso2: 'KP', flag: '🇰🇵', dialCode: '+850' },
  { name: 'North Macedonia', iso2: 'MK', flag: '🇲🇰', dialCode: '+389' },
  { name: 'Northern Mariana Islands', iso2: 'MP', flag: '🇲🇵', dialCode: '+1670' },
  { name: 'Norway', iso2: 'NO', flag: '🇳🇴', dialCode: '+47' },
  { name: 'Oman', iso2: 'OM', flag: '🇴🇲', dialCode: '+968' },
  { name: 'Pakistan', iso2: 'PK', flag: '🇵🇰', dialCode: '+92' },
  { name: 'Palau', iso2: 'PW', flag: '🇵🇼', dialCode: '+680' },
  { name: 'Palestine', iso2: 'PS', flag: '🇵🇸', dialCode: '+970' },
  { name: 'Panama', iso2: 'PA', flag: '🇵🇦', dialCode: '+507' },
  { name: 'Papua New Guinea', iso2: 'PG', flag: '🇵🇬', dialCode: '+675' },
  { name: 'Paraguay', iso2: 'PY', flag: '🇵🇾', dialCode: '+595' },
  { name: 'Peru', iso2: 'PE', flag: '🇵🇪', dialCode: '+51' },
  { name: 'Philippines', iso2: 'PH', flag: '🇵🇭', dialCode: '+63' },
  { name: 'Pitcairn Islands', iso2: 'PN', flag: '🇵🇳', dialCode: '+64' },
  { name: 'Poland', iso2: 'PL', flag: '🇵🇱', dialCode: '+48' },
  { name: 'Portugal', iso2: 'PT', flag: '🇵🇹', dialCode: '+351' },
  { name: 'Puerto Rico', iso2: 'PR', flag: '🇵🇷', dialCode: '+1' },
  { name: 'Qatar', iso2: 'QA', flag: '🇶🇦', dialCode: '+974' },
  { name: 'Republic of the Congo', iso2: 'CG', flag: '🇨🇬', dialCode: '+242' },
  { name: 'Réunion', iso2: 'RE', flag: '🇷🇪', dialCode: '+262' },
  { name: 'Romania', iso2: 'RO', flag: '🇷🇴', dialCode: '+40' },
  { name: 'Russia', iso2: 'RU', flag: '🇷🇺', dialCode: '+7' },
  { name: 'Rwanda', iso2: 'RW', flag: '🇷🇼', dialCode: '+250' },
  { name: 'Saint Barthélemy', iso2: 'BL', flag: '🇧🇱', dialCode: '+590' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', iso2: 'SH', flag: '🇸🇭', dialCode: '+290' },
  { name: 'Saint Kitts and Nevis', iso2: 'KN', flag: '🇰🇳', dialCode: '+1869' },
  { name: 'Saint Lucia', iso2: 'LC', flag: '🇱🇨', dialCode: '+1758' },
  { name: 'Saint Martin', iso2: 'MF', flag: '🇲🇫', dialCode: '+590' },
  { name: 'Saint Pierre and Miquelon', iso2: 'PM', flag: '🇵🇲', dialCode: '+508' },
  { name: 'Saint Vincent and the Grenadines', iso2: 'VC', flag: '🇻🇨', dialCode: '+1784' },
  { name: 'Samoa', iso2: 'WS', flag: '🇼🇸', dialCode: '+685' },
  { name: 'San Marino', iso2: 'SM', flag: '🇸🇲', dialCode: '+378' },
  { name: 'São Tomé and Príncipe', iso2: 'ST', flag: '🇸🇹', dialCode: '+239' },
  { name: 'Saudi Arabia', iso2: 'SA', flag: '🇸🇦', dialCode: '+966' },
  { name: 'Senegal', iso2: 'SN', flag: '🇸🇳', dialCode: '+221' },
  { name: 'Serbia', iso2: 'RS', flag: '🇷🇸', dialCode: '+381' },
  { name: 'Seychelles', iso2: 'SC', flag: '🇸🇨', dialCode: '+248' },
  { name: 'Sierra Leone', iso2: 'SL', flag: '🇸🇱', dialCode: '+232' },
  { name: 'Singapore', iso2: 'SG', flag: '🇸🇬', dialCode: '+65' },
  { name: 'Sint Maarten', iso2: 'SX', flag: '🇸🇽', dialCode: '+1721' },
  { name: 'Slovakia', iso2: 'SK', flag: '🇸🇰', dialCode: '+421' },
  { name: 'Slovenia', iso2: 'SI', flag: '🇸🇮', dialCode: '+386' },
  { name: 'Solomon Islands', iso2: 'SB', flag: '🇸🇧', dialCode: '+677' },
  { name: 'Somalia', iso2: 'SO', flag: '🇸🇴', dialCode: '+252' },
  { name: 'South Africa', iso2: 'ZA', flag: '🇿🇦', dialCode: '+27' },
  { name: 'South Georgia', iso2: 'GS', flag: '🇬🇸', dialCode: '+500' },
  { name: 'South Korea', iso2: 'KR', flag: '🇰🇷', dialCode: '+82' },
  { name: 'South Sudan', iso2: 'SS', flag: '🇸🇸', dialCode: '+211' },
  { name: 'Spain', iso2: 'ES', flag: '🇪🇸', dialCode: '+34' },
  { name: 'Sri Lanka', iso2: 'LK', flag: '🇱🇰', dialCode: '+94' },
  { name: 'Sudan', iso2: 'SD', flag: '🇸🇩', dialCode: '+249' },
  { name: 'Suriname', iso2: 'SR', flag: '🇸🇷', dialCode: '+597' },
  { name: 'Svalbard and Jan Mayen', iso2: 'SJ', flag: '🇸🇯', dialCode: '+47' },
  { name: 'Sweden', iso2: 'SE', flag: '🇸🇪', dialCode: '+46' },
  { name: 'Switzerland', iso2: 'CH', flag: '🇨🇭', dialCode: '+41' },
  { name: 'Syria', iso2: 'SY', flag: '🇸🇾', dialCode: '+963' },
  { name: 'Taiwan', iso2: 'TW', flag: '🇹🇼', dialCode: '+886' },
  { name: 'Tajikistan', iso2: 'TJ', flag: '🇹🇯', dialCode: '+992' },
  { name: 'Tanzania', iso2: 'TZ', flag: '🇹🇿', dialCode: '+255' },
  { name: 'Thailand', iso2: 'TH', flag: '🇹🇭', dialCode: '+66' },
  { name: 'Timor-Leste', iso2: 'TL', flag: '🇹🇱', dialCode: '+670' },
  { name: 'Togo', iso2: 'TG', flag: '🇹🇬', dialCode: '+228' },
  { name: 'Tokelau', iso2: 'TK', flag: '🇹🇰', dialCode: '+690' },
  { name: 'Tonga', iso2: 'TO', flag: '🇹🇴', dialCode: '+676' },
  { name: 'Trinidad and Tobago', iso2: 'TT', flag: '🇹🇹', dialCode: '+1868' },
  { name: 'Tunisia', iso2: 'TN', flag: '🇹🇳', dialCode: '+216' },
  { name: 'Türkiye', iso2: 'TR', flag: '🇹🇷', dialCode: '+90' },
  { name: 'Turkmenistan', iso2: 'TM', flag: '🇹🇲', dialCode: '+993' },
  { name: 'Turks and Caicos Islands', iso2: 'TC', flag: '🇹🇨', dialCode: '+1649' },
  { name: 'Tuvalu', iso2: 'TV', flag: '🇹🇻', dialCode: '+688' },
  { name: 'Uganda', iso2: 'UG', flag: '🇺🇬', dialCode: '+256' },
  { name: 'Ukraine', iso2: 'UA', flag: '🇺🇦', dialCode: '+380' },
  { name: 'United Arab Emirates', iso2: 'AE', flag: '🇦🇪', dialCode: '+971' },
  { name: 'United Kingdom', iso2: 'GB', flag: '🇬🇧', dialCode: '+44' },
  { name: 'United States', iso2: 'US', flag: '🇺🇸', dialCode: '+1' },
  { name: 'United States Minor Outlying Islands', iso2: 'UM', flag: '🇺🇲', dialCode: '+1' },
  { name: 'United States Virgin Islands', iso2: 'VI', flag: '🇻🇮', dialCode: '+1340' },
  { name: 'Uruguay', iso2: 'UY', flag: '🇺🇾', dialCode: '+598' },
  { name: 'Uzbekistan', iso2: 'UZ', flag: '🇺🇿', dialCode: '+998' },
  { name: 'Vanuatu', iso2: 'VU', flag: '🇻🇺', dialCode: '+678' },
  { name: 'Vatican City', iso2: 'VA', flag: '🇻🇦', dialCode: '+379' },
  { name: 'Venezuela', iso2: 'VE', flag: '🇻🇪', dialCode: '+58' },
  { name: 'Vietnam', iso2: 'VN', flag: '🇻🇳', dialCode: '+84' },
  { name: 'Wallis and Futuna', iso2: 'WF', flag: '🇼🇫', dialCode: '+681' },
  { name: 'Western Sahara', iso2: 'EH', flag: '🇪🇭', dialCode: '+212' },
  { name: 'Yemen', iso2: 'YE', flag: '🇾🇪', dialCode: '+967' },
  { name: 'Zambia', iso2: 'ZM', flag: '🇿🇲', dialCode: '+260' },
  { name: 'Zimbabwe', iso2: 'ZW', flag: '🇿🇼', dialCode: '+263' },
];

export const DEFAULT_COUNTRY_ISO2 = 'SA';

export function findCountryByIso2(iso2: string): Country | undefined {
  return countries.find((c) => c.iso2 === iso2);
}
